import pandas as pd
from ta.momentum import RSIIndicator, StochRSIIndicator
from ta.trend import EMAIndicator, MACD
from ta.volatility import BollingerBands, AverageTrueRange
from ta.volume import VolumeWeightedAveragePrice

class IndicatorEngine:
    """
    Applies technical indicators to a pandas DataFrame containing OHLCV data.
    """
    
    @staticmethod
    def add_all_indicators(df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculates and appends RSI, MACD, EMAs, BB, ATR, StochRSI to the dataframe.
        Modifies df in-place, but also returns it.
        """
        # Ensure we have data
        if df.empty or len(df) < 200:
            return df # Need sufficient data for EMA200
            
        close = df['close']
        high = df['high']
        low = df['low']

        # RSI (14)
        rsi = RSIIndicator(close=close, window=14)
        df['RSI'] = rsi.rsi()

        # Stochastic RSI (14, 3, 3)
        stoch_rsi = StochRSIIndicator(close=close, window=14, smooth1=3, smooth2=3)
        df['StochRSI_k'] = stoch_rsi.stochrsi_k()
        df['StochRSI_d'] = stoch_rsi.stochrsi_d()

        # MACD (12, 26, 9)
        macd = MACD(close=close, window_slow=26, window_fast=12, window_sign=9)
        df['MACD'] = macd.macd()
        df['MACD_signal'] = macd.macd_signal()
        df['MACD_hist'] = macd.macd_diff()

        # EMAs (20, 50, 200)
        df['EMA_20'] = EMAIndicator(close=close, window=20).ema_indicator()
        df['EMA_50'] = EMAIndicator(close=close, window=50).ema_indicator()
        df['EMA_200'] = EMAIndicator(close=close, window=200).ema_indicator()

        # Bollinger Bands (20, 2)
        bb = BollingerBands(close=close, window=20, window_dev=2)
        df['BB_high'] = bb.bollinger_hband()
        df['BB_low'] = bb.bollinger_lband()
        df['BB_mid'] = bb.bollinger_mavg()

        # ATR (14)
        atr = AverageTrueRange(high=high, low=low, close=close, window=14)
        df['ATR'] = atr.average_true_range()

        # VWAP
        if 'volume' in df.columns:
            vwap = VolumeWeightedAveragePrice(high=high, low=low, close=close, volume=df['volume'], window=14)
            df['VWAP'] = vwap.volume_weighted_average_price()

        # Fill NaNs generated by rolling windows backward or drop them
        df.bfill(inplace=True)
        
        return df

    @staticmethod
    def is_macd_bullish(df: pd.DataFrame) -> bool:
        """Checks if current MACD is bullish (MACD line > Signal line and histogram > 0)."""
        if df.empty or 'MACD' not in df.columns: return False
        last_row = df.iloc[-1]
        return last_row['MACD'] > last_row['MACD_signal'] and last_row['MACD_hist'] > 0

    @staticmethod
    def is_macd_bearish(df: pd.DataFrame) -> bool:
        """Checks if current MACD is bearish (MACD line < Signal line and histogram < 0)."""
        if df.empty or 'MACD' not in df.columns: return False
        last_row = df.iloc[-1]
        return last_row['MACD'] < last_row['MACD_signal'] and last_row['MACD_hist'] < 0

    @staticmethod
    def is_volume_increasing(df: pd.DataFrame, periods=3) -> bool:
        """Checks if volume has been generally increasing over the last N periods."""
        if len(df) < periods + 1: return False
        vols = df['volume'].tail(periods).values
        # Simple check: current volume > average of previous 'periods-1'
        current_vol = vols[-1]
        avg_prev_vol = vols[:-1].mean()
        return current_vol > avg_prev_vol

    @staticmethod
    def is_volume_decreasing(df: pd.DataFrame, periods=3) -> bool:
        """Checks if volume has been generally decreasing over the last N periods."""
        if len(df) < periods + 1: return False
        vols = df['volume'].tail(periods).values
        current_vol = vols[-1]
        avg_prev_vol = vols[:-1].mean()
        return current_vol < avg_prev_vol
